# Below is for Server config
server:
  port: 10190
  servlet:
    context-path: /app
#  ssl:
#    key-alias: 1
#    key-store: classpath:https/xgfe-pos-sit-ssl-keystore.jks
#    key-store-password: xgfessl10000
#    key-store-type: JKS
#    trust-store: classpath:https/cacerts
#    trust-store-password: changeit
#    trust-store-type: JKS

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  redis:
    host: localhost
  freemarker:
#    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


# 注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # 在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: debug

